### ISSUE TITLE
How to install the iOS-SandBox-Dumper

### ISSUE THREAD

**Issue by nandy6666** [dineshshetty/iOS-SandBox-Dumper#3]
How to install the iOS-SandBox-Dumper

**Comment by dineshshetty** [comment]
You can either use the Xcode project to install the app to the device, or directly install the IPA file from the releases section (direct path - https://github.com/dineshshetty/iOS-SandBox-Dumper/releases/download/v1.2/displayiOSSandboxDetails.ipa)
